
  env= "gc"
  debug= true
  print_level= "debug"

  [cluster]
    [cluster.discovery]
      mode="etcd"
#      "@mode1": "mode=default,从profile-{x}.json读取node节点的配置数据",
#      "@mode2": "mode=nats,通过nats->master_node_id获取已注册的节点",
#      "@mode3": "mode=etcd,通过etcd同步已注册节点"

    [cluster.nats]
      master_node_id="gc-master"
      address="nats://127.0.0.1:4222"
      reconnect_delay=1
      max_reconnects=0
      request_timeout=2
      user=""
      password=""
    [cluster.etcd]
      end_points="127.0.0.1:2379"
#      "@end_points"="127.0.0.1:2379"
      prefix ="cherry"
      ttl=5
      dial_timeout=3
      dial_keep_alive_time=1
      dial_keep_alive_timeout=1
      user=""
      password=""
  [cluster.consul]
      Addr = ["192.168.11.48:8500"]
      Path = "/cherry"
  [node]
    [[node.master]]
        node_id="gc-master"
        address=""
        enable=true
      [node.master.__settings__]
        ref_logger="master_log"

    [[node.center]]
        node_id="gc-center"
        address=""
        enable=true
        [node.center.__settings__]
          ref_logger="center_log"

    [[node.gate]]
        node_id="gc-gate-1"
        address=":10010"
        [node.gate.__settings__]
        ref_logger="gate_log"
        enable=true
        [node.gate.__settings__.db_id_list ]
                game_db_id="game_db_1"


    [[node.web]]
        node_id="gc-web-1"
        address="127.0.0.1:8080"
        [node.web.__settings__]
          ref_logger="master_log"
          enable=true

  [[node.game]]
        node_id="10001"
       [node.game.__settings__]
        enable=true
        ref_logger="game_log"
       [node.game.__settings__.db_id_list ]
                  game_db_id="game_db_1"


  [logger]
  [logger.master_log]
      level="debug"
      enable_console=true
      enable_write_file=false
      file_link_path="logs/master.log"
      file_path_format="logs/master_%Y%m%d%H%M.log"

  [logger.center_log]
      level="debug"
      enable_console=true
      enable_write_file=false
      file_link_path="logs/center.log"
      file_path_format="logs/center_%Y%m%d%H%M.log"

  [logger.gate_log]
      level="debug"
      enable_console=true
      enable_write_file=false
      file_link_path="logs/gate.log"
      file_path_format="logs/gate_%Y%m%d%H%M.log"

  [logger.game_log]
      level="debug"
      enable_console=true
      enable_write_file=false
      file_link_path="logs/game.log"
      file_path_format="logs/game_%Y%m%d%H%M.log"

  [logger.cross_log]
      level="debug"
      enable_console=true
      enable_write_file=false
      file_link_path="logs/cross.log"
      file_path_format="logs/cross_%Y%m%d%H%M.log"


  [data_config]
    parser="json"
    data_source="file"
      [data_config.file]
          file_path="data/"
          ext_name=".json"
          reload_time=3000

      [data_config.redis]
          prefix_key="data_config"
          subscribe_key="data_config_change"
          address="dev.com:6379"
          password=""
          db=7


